name: rc_sow_connected
description: Connected RC SOW humanitarian field-operations application.
publish_to: none
version: 19.1.0+1910

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
